# Generated by Django 2.2.13 on 2021-03-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='precio',
            new_name='punteo',
        ),
    ]
